version: '3.8'
services:
  mongo: 
    build: .
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MON_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MON_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      #- C:/dockerLocalData:/data/db
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local