version: '3.8'
services:
  mongo: 
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - C:/dockerLocalData:/data/db
      # - mongodata:/data/db
volumes:
  mongodata:
    driver: local